Implements
trocco-io/embulk-input-google_spreadsheets_java pull request #1
Opened 2024-11-11 01:36 UTC by t3t5u

2024-11-11 12:35 UTC, NamedPython commented
`SERIAL_NUMBER`

https://developers.google.com/sheets/api/reference/rest/v4/DateTimeRenderOption?hl=ja

2025-01-24 07:37 UTC, d-hrs requested changes
実装、挙動の確認行いました。問題ないと思います。
build.gradleの点だけ確認お願いします。

2025-01-24 07:37 UTC, d-hrs commented on src/main/java/org/embulk/input/google_spreadsheets_java/PluginTask.java
> +  @ConfigDefault("\"SERIAL_NUMBER\"")
[IMO] 現代において、`Lotus 1-2-3` が一般的ではないので、APIのデフォルトが `SERIAL_NUMBER` だとしても、pluginとしては `FORMATTED_STRING` がデフォルトのほうがいいのでは。と思います。
https://developers.google.com/sheets/api/reference/rest/v4/DateTimeRenderOption
> Instructs date, time, datetime, and duration fields to be output as doubles in "serial number" format, as popularized by Lotus 1-2-3. The whole number portion of the value (left of the decimal) counts the days since December 30th 1899.

2025-01-24 07:37 UTC, d-hrs commented on build.gradle
> +    implementation "org.embulk:embulk-util-config:0.3.4"
脆弱性があるようです。
![image](https://github.com/user-attachments/assets/75b7a878-f05e-4ab5-b87a-4981185dd56f)

2025-01-24 07:37 UTC, d-hrs commented on build.gradle
> +    implementation "org.embulk:embulk-util-config:0.3.4"
embulk-util-jsonやembulk-util-timestampもできるだけ最新のを利用できないでしょうか。
https://mvnrepository.com/artifact/org.embulk

2025-01-24 07:37 UTC, d-hrs commented on src/main/java/org/embulk/input/google_spreadsheets_java/GoogleSpreadsheetsJavaInputPlugin.java
> +      LOGGER.warn("Error {} occurred. Skip {}", e, Arrays.toString(record.toArray()));
[NITS] 前段にinputのspreadsheetsを出力する何かのフローがあり、そのフローがバグって1カラムずれた1万行のspreadsheetsを出力してしまった場合に、1万行のwarnが出力されます。
stop_on_invalid_recordのデフォルトがtrueなので基本的には問題ないのですが、例外的にそのような挙動にもなりうるので、出力の抑制(N行以下は出力しない)などの仕組みがあるとよりよさそうです。

2025-01-24 07:37 UTC, d-hrs commented on src/main/java/org/embulk/input/google_spreadsheets_java/Pager.java
> +      if (fetchedRows < maxFetchRows) {
📝 ここの `break` には意味がないように見えるが、 次のような空行を含むシートの場合に、空行が含まれる場合にデータの取得を止めるのに必要。
![image](https://github.com/user-attachments/assets/66b88d49-5a4d-4634-bdd5-99204b64c106)

空行を含む場合に止まるのが正しいのかどうかは別途議論が必要だが、rubyの実装でも同様の実装になっている
https://github.com/medjed/embulk-input-google_spreadsheets/blob/master/lib/embulk/input/google_spreadsheets/pager.rb#L50

2025-01-24 08:37 UTC, t3t5u commented on build.gradle
> +    implementation "org.embulk:embulk-util-config:0.3.4"
Embulk v0.9 のランタイムの [Jackson 2.6.7](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.6.7) と[バージョンを揃える必要があるため](https://zenn.dev/hiroysato/articles/b910af4c581bdb#jackson-%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3)
embulk-util-config は [0.3.4](https://mvnrepository.com/artifact/org.embulk/embulk-util-config/0.3.4) までしか上げられません ([0.4.0](https://mvnrepository.com/artifact/org.embulk/embulk-util-config/0.4.0) は [Jackson 2.15.3](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.3) 以上に依存しています)
同様の理由で embulk-util-json も [0.3.0](https://mvnrepository.com/artifact/org.embulk/embulk-util-json/0.3.0) までしか上げられません
なお embulk-spi の [0.11](https://mvnrepository.com/artifact/org.embulk/embulk-spi/0.11) と embulk-util-timestamp の [0.3.0](https://mvnrepository.com/artifact/org.embulk/embulk-util-timestamp/0.3.0) は最新です

2025-01-24 08:40 UTC, t3t5u commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
最新の gradle-embulk-plugins [v0.7.0](https://github.com/embulk/gradle-embulk-plugins/tree/v0.7.0) に[合わせています](https://github.com/embulk/gradle-embulk-plugins/tree/v0.7.0?tab=readme-ov-file#versions)

2025-01-24 10:30 UTC, t3t5u commented on src/main/java/org/embulk/input/google_spreadsheets_java/typecast/TypeCast.java
> +  public abstract Value asJson(Object value);
Embulk v0.9 で `type: json` にすると `NoClassDefFoundError` になる問題を修正しました
```
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/embulk/spi/json/JsonValue
```

2025-01-27 04:12 UTC, d-hrs approved these changes
LGTM

2025-01-27 04:12 UTC, merged